name: Build and Test Server Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-and-run:
    name: Build and Run Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Variables
        id: variables
        run: |
          echo "::set-output name=datetime::$(date +%Y%m%dT%H%M%SZ)"
          echo "::set-output name=userid::$(id -u)"
          echo "::set-output name=groupid::$(id -g)"

      - name: Set Permissions on Executable Scripts
        run: |
          chmod +x src/install_server.scmd
          chmod +x src/run_server.sh

      - name: Make Directories
        run: mkdir ZomboidConfig ZomboidDedicatedServer

      - name: Build the Docker Image
        if: ${{ success() }}
        run: |
          docker build \
          --file docker/zomboid-dedicated-server.Dockerfile \
          --tag renegademaster/zomboid-dedicated-server:${{ steps.variables.outputs.datetime }} \
          --build-arg USER_ID=${{ steps.variables.outputs.userid }} \
          --build-arg GROUP_ID=${{ steps.variables.outputs.groupid }} \
          .

      - name: Test Run the Docker Image
        if: ${{ success() }}
        continue-on-error: true
        timeout-minutes: 5
        run: |
          docker run \
          --rm \
          --name zomboid-dedicated-server \
          --user ${{ steps.variables.outputs.userid }}:${{ steps.variables.outputs.groupid }} \
          --mount type=bind,source="$(pwd)/ZomboidDedicatedServer",target=/home/steam/ZomboidDedicatedServer \
          --mount type=bind,source="$(pwd)/ZomboidConfig",target=/home/steam/Zomboid \
          --env=AUTOSAVE_INTERVAL="16"
          --env=GAME_PORT="25496"
          --env=MAX_PLAYERS="14"
          --env=MAX_RAM="6144m"
          --env=PAUSE_ON_EMPTY="true"
          --env=PUBLIC_SERVER="false"
          --env=SERVER_NAME="GitHub Action Test Server Name"
          --env=SERVER_PASSWORD="github_action_test_password"
          renegademaster/zomboid-dedicated-server:${{ steps.variables.outputs.datetime }} \
          2>&1 | tee ./docker-log.log

      - name: Investigate File Structure on Failure
        if: ${{ failure() }}
        run: |
          pwd
          echo ''
          ls -lAuhFn ./ZomboidDedicatedServer/
          echo ''
          ls -lAuhFn ./ZomboidConfig/
          echo ''
          tree -aL 4 ./ZomboidDedicatedServer/
          echo ''
          tree -aL 4 ./ZomboidConfig/

      - name: Upload Docker Logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: docker-logs
          path: |
            docker-log.log

      - name: Upload Server Configuration
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: server-configs
          path: |
            ZomboidConfig/Server/*.ini
            ZomboidConfig/Server/*_SandboxVars.lua
            ZomboidDedicatedServer/ProjectZomboid64.json

  test:
    name: Test Server
    runs-on: ubuntu-latest
    needs:
      - build-and-run
    steps:
      - name: Download Docker Logs
        uses: actions/download-artifact@v2
        with:
          name: docker-logs

      - name: Download Server Configs
        uses: actions/download-artifact@v2
        with:
          name: server-configs

      - name: Test - Server Started
        run: |
          grep -q -iE "LuaNet: Initialization \[DONE\]" "./docker-log.log"

      - name: Test - Sed Command Completed
        run: |
          ! grep -q -iE "sed: can't read" "./docker-log.log"

      - name: Test - Server JVM Configuration Applied
        run: |
          grep -q -iE "\-Xmx6144m" "./ZomboidDedicatedServer/ProjectZomboid64.json"

      - name: Test - Server Configuration Applied
        run: |
          grep -q -iE "SaveWorldEveryMinutes=16" "./ZomboidConfig/Server/*.ini"
          grep -q -iE "SteamPort1=25496" "./ZomboidConfig/Server/*.ini"
          grep -q -iE "MaxPlayers=14" "./ZomboidConfig/Server/*.ini"
          grep -q -iE "PauseEmpty=true" "./ZomboidConfig/Server/*.ini"
          grep -q -iE "Open=false" "./ZomboidConfig/Server/*.ini"
          grep -q -iE "PublicName=GitHub Action Test Server Name" "./ZomboidConfig/Server/*.ini"
          grep -q -iE "Password=github_action_test_password" "./ZomboidConfig/Server/*.ini"
